Repository elastic/ecs-logging-go-zap, pull requests merged in 2021-01, with the labels that each got.

#25 ci: use gotestsum to generate junit output
  .ci/scripts/run-tests.sh
Labels: automation, ci, team:automation

#26 ci: add /test comment trigger
  .ci/Jenkinsfile
Labels: automation, ci, team:automation

#27 ci: install tools from CI
  .ci/Jenkinsfile
  .ci/scripts/run-tests.sh
Labels: automation, ci, team:automation

#21 fix: Change `stacktrace` to `stack_trace`
  CHANGELOG.md
  README.md
  encoder_config.go
  encoder_config_test.go
  internal/error.go
  internal/error_test.go
Labels: review

#22 add: ecszap.WrapCoreOption
  CHANGELOG.md
  README.md
  core.go
  logger_test.go
Labels: review

#23 Add common spec and run validation against it
  CHANGELOG.md
  README.md
  core_test.go
  encoder_config.go
  encoder_config_test.go
  internal/spec/spec.go
  internal/spec/v1.json
  logger_test.go
Labels: review

#29 Initialize docs
  .gitignore
  docs/index.asciidoc
  docs/introduction.asciidoc
  docs/setup.asciidoc
Labels: documentation

#30 Remove docs from readme
  README.md
Labels: documentation

#28 ci: use goTestJUnit for run the tests
  .ci/Jenkinsfile
  .ci/scripts/run-tests.sh
Labels: automation, chore, ci, team:automation
